name: build-standalone

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.5'
          cabal-version: '3.12.1.0'

      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgmp-dev libffi-dev zlib1g-dev pkg-config libblst-dev
          cabal update
          cabal build exe:cardano-loans

      - run: |
          BIN="$(cabal list-bin exe:cardano-loans)"
          cp "$BIN" cardano-loans-linux-x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: cardano-loans-linux-x86_64
          path: cardano-loans-linux-x86_64
